"""
Full evaluation: Extractive | Abstractive | Hybrid
Metrics: ROUGE-1, ROUGE-2, ROUGE-L, BERTScore (F1)
"""
import sys
import os
import json
import glob
import time
import numpy as np
from tqdm import tqdm

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import src.utils

from rouge_score import rouge_scorer
from bert_score import score as bert_score_fn

from src.extractive import extractive_compress
from src.abstractive import AraT5Summarizer
from src.postprocess import postprocess_summary
from src.utils import find_model_dir


class ArabicTokenizer:
    def tokenize(self, text):
        return text.split()



BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = find_model_dir(os.path.join(BASE_DIR, "models", "arat5-xlsum-best"))

TEST_PATH = os.path.join(BASE_DIR, "data", "test_articles_raw.json")
OUTPUT_PATH = os.path.join(BASE_DIR, "full_evaluation_report.json")

MAX_SAMPLES = 200  



def load_test_data(path):
    if not os.path.exists(path):
        print(f"⚠️ Test file not found: {path}")
        _suggest_data_files(BASE_DIR)
        print("\nCreating dummy test data for demo...")
        return [
            {
                "id": "demo_1",
                "text": "أعلنت السلطات اليوم عن إطلاق مشروع جديد للطاقة الشمسية في الصحراء الغربية. يهدف المشروع إلى توفير الكهرباء لأكثر من مليون منزل. وقال وزير الطاقة إن هذا المشروع سيكون الأكبر من نوعه في المنطقة.",
                "summary": "أعلنت السلطات عن إطلاق أكبر مشروع للطاقة الشمسية في الصحراء الغربية لتوفير الكهرباء لمليون منزل."
            },
            {
                "id": "demo_2",
                "text": "فاز المنتخب الوطني لكرة القدم على نظيره المصري بهدفين مقابل هدف واحد. أحرز الهدف الأول اللاعب أحمد في الدقيقة 25، ثم أضاف اللاعب محمد الهدف الثاني في الدقيقة 78. بهذا الفوز تأهل المنتخب إلى الدور نصف النهائي.",
                "summary": "فاز المنتخب الوطني على مصر بهدفين مقابل هدف وتأهل إلى نصف النهائي."
            },
            {
                "id": "demo_3",
                "text": "أطلقت شركة التكنولوجيا العملاقة هاتفها الذكي الجديد الذي يتميز ببطارية تدوم 48 ساعة. يأتي الهاتف بشاشة مقاس 6.7 بوصة ومعالج من الجيل الخامس. وسيبدأ سعر الهاتف من 899 دولاراً.",
                "summary": "أطلقت شركة تكنولوجيا هاتفاً ذكياً جديداً ببطارية تدوم 48 ساعة وسعر يبدأ من 899 دولاراً."
            }
        ]
    
    if path.endswith('.jsonl'):
        with open(path, "r", encoding="utf-8") as f:
            data = [json.loads(line) for line in f if line.strip()]
    else:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    
    if isinstance(data, dict):
        for key in ["samples", "data", "articles", "records", "items", "test"]:
            if key in data and isinstance(data[key], list):
                data = data[key]
                break
        else:
            data = [data]
    
    if not data:
        raise ValueError("Dataset is empty")
    
    first = data[0]
    if not isinstance(first, dict):
        raise TypeError(f"Expected list of dicts, got {type(first).__name__}")
    
    keys = set(first.keys())
    

    result_keys = {"prediction", "reference", "rouge1", "rouge2", "rougeL"}
    if result_keys.issubset(keys):
        raise ValueError(
            f"\n{'='*70}\n"
            f"❌ ERROR: You pointed TEST_PATH to an evaluation RESULTS file,\n"
            f"   not a raw dataset.\n\n"
            f"   File: {path}\n"
            f"   Detected keys: {sorted(keys)}\n\n"
            f"   This file contains 'prediction', 'reference', 'rouge1'...\n"
            f"   which means it was generated by a previous evaluation run.\n\n"
            f"   The pipeline needs the ORIGINAL dataset with:\n"
            f"   - Article text (e.g., 'text', 'article', 'document')\n"
            f"   - Reference summary (e.g., 'summary', 'headline')\n\n"
            f"   FIX: Change TEST_PATH in evaluate.py to point to your actual dataset.\n"
            f"{'='*70}"
        )
    
    text_candidates = ["text", "article", "document", "content", "body", "input", "source"]
    text_key = next((k for k in text_candidates if k in keys), None)
    
    summary_candidates = ["summary", "headline", "abstract", "target", "output", "title", "summary_text", "reference"]
    summary_key = next((k for k in summary_candidates if k in keys), None)
    
    id_candidates = ["id", "ID", "sample_id", "doc_id", "index"]
    id_key = next((k for k in id_candidates if k in keys), None)
    
    if not text_key:
        print(f"\n⚠️ Available keys in your file: {sorted(keys)}")
        _suggest_data_files(BASE_DIR)
        raise KeyError(
            f"Could not find article field.\n"
            f"Expected one of: {text_candidates}\n"
            f"Please check your dataset format or change TEST_PATH."
        )
    if not summary_key:
        print(f"\n⚠️ Available keys in your file: {sorted(keys)}")
        raise KeyError(
            f"Could not find summary field.\n"
            f"Expected one of: {summary_candidates}"
        )
    
    print(f"✅ Auto-detected fields — article: '{text_key}', summary: '{summary_key}', id: '{id_key or 'index'}'")
    print(f"✅ Loaded {len(data)} test articles")
    
    normalized = []
    for idx, item in enumerate(data):
        if not isinstance(item, dict):
            continue
            
        norm = {
            "id": str(item.get(id_key, idx)) if id_key else str(idx),
            "text": str(item.get(text_key, "")).strip(),
            "summary": str(item.get(summary_key, "")).strip()
        }
        
        if not norm["text"]:
            print(f"⚠️ Warning: item {norm['id']} has empty text")
        if not norm["summary"]:
            print(f"⚠️ Warning: item {norm['id']} has empty summary")
            
        normalized.append(norm)
    
    normalized = [d for d in normalized if d["text"]]
    
    if not normalized:
        raise ValueError("No valid samples found after filtering empty texts")
    
    print(f"✅ Final valid samples: {len(normalized)}")
    print(f"Sample keys: {list(normalized[0].keys())}")
    return normalized


def _suggest_data_files(base_dir):
    """Scan data/ folder and suggest valid dataset files."""
    data_dir = os.path.join(base_dir, "data")
    if not os.path.exists(data_dir):
        return
    candidates = glob.glob(os.path.join(data_dir, "*.json")) + glob.glob(os.path.join(data_dir, "*.jsonl"))
    if candidates:
        print(f"\n📁 Found these files in data/ folder:")
        for c in candidates:
            print(f"   - {os.path.basename(c)}")
        print(f"\n💡 Try changing TEST_PATH to one of these.")



rouge_scorer_obj = rouge_scorer.RougeScorer(
    ['rouge1', 'rouge2', 'rougeL'],
    use_stemmer=False,
    tokenizer=ArabicTokenizer()
)


def compute_rouge(pred, ref):
    scores = rouge_scorer_obj.score(ref, pred)
    return {
        "rouge1": round(scores['rouge1'].fmeasure * 100, 4),
        "rouge2": round(scores['rouge2'].fmeasure * 100, 4),
        "rougeL": round(scores['rougeL'].fmeasure * 100, 4),
    }


def compute_bertscore(preds, refs):
    """Compute BERTScore. Returns None if offline."""
    try:
        P, R, F1 = bert_score_fn(
            preds,
            refs,
            lang="ar",
            model_type="bert-base-multilingual-cased",
            num_layers=9,
            verbose=False,
            device="cuda" if os.system("nvidia-smi > /dev/null 2>&1") == 0 else "cpu"
        )
        return [round(f * 100, 4) for f in F1.tolist()]
    except Exception as e:
        print(f"⚠️ BERTScore skipped: {e}")
        return [None] * len(preds)



def run_extractive(articles, max_sentences=5):
    return [extractive_compress(a, max_sentences=max_sentences) for a in tqdm(articles, desc="Extractive")]


def run_abstractive(articles, model_path):
    summarizer = AraT5Summarizer(model_path)
    preds = []
    for article in tqdm(articles, desc="Abstractive"):
        pred = summarizer.summarize("summarize: " + article)
        preds.append(pred)
    return preds


def run_hybrid(articles, model_path, max_sentences=5, max_words=60):
    summarizer = AraT5Summarizer(model_path)
    preds = []
    for article in tqdm(articles, desc="Hybrid"):
        ext = extractive_compress(article, max_sentences=max_sentences)
        raw = summarizer.summarize(ext)
        final = postprocess_summary(raw, max_words=max_words)
        preds.append(final)
    return preds



def main():
    print("=" * 70)
    print("ARABIC SUMMARIZATION — FULL EVALUATION")
    print("=" * 70)
    
    # Load data
    data = load_test_data(TEST_PATH)
    if MAX_SAMPLES:
        data = data[:MAX_SAMPLES]
        print(f"Evaluating on {MAX_SAMPLES} samples (subset mode)")
    else:
        print(f"Evaluating on {len(data)} samples (full test set)")
    
    articles = [d["text"] for d in data]
    refs = [d["summary"] for d in data]
    
    results = {
        "metadata": {
            "total_samples": len(data),
            "model_path": MODEL_PATH,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
        },
        "pipelines": {}
    }
    
    print("\n" + "=" * 70)
    print("1. EXTRACTIVE PIPELINE")
    print("=" * 70)
    ext_preds = run_extractive(articles)
    
    ext_rouge1, ext_rouge2, ext_rougeL = [], [], []
    for pred, ref in zip(ext_preds, refs):
        r = compute_rouge(pred, ref)
        ext_rouge1.append(r["rouge1"])
        ext_rouge2.append(r["rouge2"])
        ext_rougeL.append(r["rougeL"])
    
    results["pipelines"]["extractive"] = {
        "avg_rouge1": round(np.mean(ext_rouge1), 4),
        "avg_rouge2": round(np.mean(ext_rouge2), 4),
        "avg_rougeL": round(np.mean(ext_rougeL), 4),
        "avg_bertscore": None,
        "samples": [
            {"id": data[i].get("id", i), "pred": ext_preds[i], "ref": refs[i],
             "rouge1": ext_rouge1[i], "rouge2": ext_rouge2[i], "rougeL": ext_rougeL[i]}
            for i in range(len(data))
        ]
    }
    print(f"ROUGE-1:  {results['pipelines']['extractive']['avg_rouge1']}")
    print(f"ROUGE-2:  {results['pipelines']['extractive']['avg_rouge2']}")
    print(f"ROUGE-L:  {results['pipelines']['extractive']['avg_rougeL']}")
    
    print("\n" + "=" * 70)
    print("2. ABSTRACTIVE PIPELINE (AraT5 direct)")
    print("=" * 70)
    abs_preds = run_abstractive(articles, MODEL_PATH)
    
    abs_rouge1, abs_rouge2, abs_rougeL = [], [], []
    for pred, ref in zip(abs_preds, refs):
        r = compute_rouge(pred, ref)
        abs_rouge1.append(r["rouge1"])
        abs_rouge2.append(r["rouge2"])
        abs_rougeL.append(r["rougeL"])
    
    print("Computing BERTScore...")
    abs_bert = compute_bertscore(abs_preds, refs)
    
    results["pipelines"]["abstractive"] = {
        "avg_rouge1": round(np.mean(abs_rouge1), 4),
        "avg_rouge2": round(np.mean(abs_rouge2), 4),
        "avg_rougeL": round(np.mean(abs_rougeL), 4),
        "avg_bertscore": round(np.mean([b for b in abs_bert if b is not None]), 4) if any(b is not None for b in abs_bert) else None,
        "samples": [
            {"id": data[i].get("id", i), "pred": abs_preds[i], "ref": refs[i],
             "rouge1": abs_rouge1[i], "rouge2": abs_rouge2[i], "rougeL": abs_rougeL[i],
             "bertscore": abs_bert[i]}
            for i in range(len(data))
        ]
    }
    print(f"ROUGE-1:    {results['pipelines']['abstractive']['avg_rouge1']}")
    print(f"ROUGE-2:    {results['pipelines']['abstractive']['avg_rouge2']}")
    print(f"ROUGE-L:    {results['pipelines']['abstractive']['avg_rougeL']}")
    print(f"BERTScore:  {results['pipelines']['abstractive']['avg_bertscore']}")
    
    # ── 3. FULL HYBRID ──
    print("\n" + "=" * 70)
    print("3. HYBRID PIPELINE (Extractive → AraT5 → Post-process)")
    print("=" * 70)
    hybrid_preds = run_hybrid(articles, MODEL_PATH)
    
    hyb_rouge1, hyb_rouge2, hyb_rougeL = [], [], []
    for pred, ref in zip(hybrid_preds, refs):
        r = compute_rouge(pred, ref)
        hyb_rouge1.append(r["rouge1"])
        hyb_rouge2.append(r["rouge2"])
        hyb_rougeL.append(r["rougeL"])
    
    print("Computing BERTScore...")
    hyb_bert = compute_bertscore(hybrid_preds, refs)
    
    results["pipelines"]["hybrid"] = {
        "avg_rouge1": round(np.mean(hyb_rouge1), 4),
        "avg_rouge2": round(np.mean(hyb_rouge2), 4),
        "avg_rougeL": round(np.mean(hyb_rougeL), 4),
        "avg_bertscore": round(np.mean([b for b in hyb_bert if b is not None]), 4) if any(b is not None for b in hyb_bert) else None,
        "samples": [
            {"id": data[i].get("id", i), "pred": hybrid_preds[i], "ref": refs[i],
             "rouge1": hyb_rouge1[i], "rouge2": hyb_rouge2[i], "rougeL": hyb_rougeL[i],
             "bertscore": hyb_bert[i]}
            for i in range(len(data))
        ]
    }
    print(f"ROUGE-1:    {results['pipelines']['hybrid']['avg_rouge1']}")
    print(f"ROUGE-2:    {results['pipelines']['hybrid']['avg_rouge2']}")
    print(f"ROUGE-L:    {results['pipelines']['hybrid']['avg_rougeL']}")
    print(f"BERTScore:  {results['pipelines']['hybrid']['avg_bertscore']}")
    
    print("\n" + "=" * 70)
    print("SUMMARY COMPARISON")
    print("=" * 70)
    print(f"{'Pipeline':<<20} {'ROUGE-1':<<12} {'ROUGE-2':<<12} {'ROUGE-L':<<12} {'BERTScore':<<12}")
    print("-" * 70)
    for name, pipe in results["pipelines"].items():
        bert = str(pipe['avg_bertscore']) if pipe['avg_bertscore'] is not None else "N/A"
        print(f"{name:<20} {pipe['avg_rouge1']:<12} {pipe['avg_rouge2']:<12} {pipe['avg_rougeL']:<12} {bert:<12}")
    
    # Save report
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    
    print(f"\n✅ Full report saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()